[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "ollama>=0.5.1",
    "scikit-learn>=1.7.0",
    "sentence-transformers>=4.1.0",
]
